version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev